// <auto-generated />
namespace Kilo.TestConsole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204302155491_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVZW2/bNhR+H7D/IOhxQCXHw4o2sFtkuRTB5iSI0r4GjHTsEKVIlaQy+7ftYT9pf2GHulkiZcvKmmB7MWzq3M/Hc5H//vOv2cd1yrwnkIoKPvePgonvAY9FQvlq7ud6+ead//HDjz/MzpN07X2p6aaGDjm5mvuPWmfHYajiR0iJClIaS6HEUgexSEOSiHA6mbwLjyYhoAgfZXne7DbnmqZQ/MCfp4LHkOmcsIVIgKnqHJ9EhVTviqSgMhLD3I9omjGKFkJwIfH4DyG/BnegNApRgoHvnTBK0K4I2HKkkZP3xki/UY8GnKOhenO3yaAwYu5/ViDbFEjzG2w6B3h0I0UGUm9uYVnxXSa+F3b5QpuxYWvxGNVz/1NO8ftVzhh5YPh7SZgCR6DFbj5rAZGWmFLfu6BrSH4HvtKPjZQFWdcnv2BeP/MivHNfyxyGlV6RJ7oiGnFhqT9PCWUnSSJBKd+7BVYQqUealckJTCjvu1QXUqS3glVx7jy8j0QuY+OQ2EVxR+QKdNfCWbhN4d7Edgx59QRfcv3ztCfY2dvjSAsJn4CDJBqSG6I1SG54oXChwvhx9vYwmL8PJ1MD85BwLnSRkyEgfSEsH4uk6Vgo7UrUiVIipoWdrSt4vydd5zzxBkFU+lLDEE3PmaamsqAJc/8nJyT7hNa4awntwrorfBIER7bvLS9dlGJp04QiAKoALIoTWGvHcUMdgW4FCrVv49rx2HGwy9z2APqkdF20pLX86dpjXfgW3c6qYN+9Q/LbeNNEIRwjps5oS4wdD/uudz3uAXaTxW17C8v+VvfBcEcjnC1IluGlazXG6sSLyq54+iYa3+vSUkYYq56W11jbaMIyRFZgPUXVaOkFlUqfEU0eiLnWp0nqkA1ittbThq6bshqDNbX5XnIMDQaB27nbkUSeVYoVtfATLPi4bMVsQhiRPRX9VLA85bu6wj7usmO3+csTV8IstOy2QxU6sbLwagf+oLRYl+C75mffnT8gT/vZXyZfVWNsC6iOXj9j3frj3iar8I68OBb3IZfEFFgrXjsLrRutg7LVEdWXOhO0xojn2Ff1k2faN9okDHlCi1HnUplpqZmURnhttyIXLU5HskkarDadyepAs6obDO9rTnsoSXwPQ/BEE9Maoo3SkAaGIIi+sVNG8XZsCRaE0yXC8U58BbN7Yvd6/pLXTL9KJey/uOnlnH7LgRbD/ZKaOe1fbH38icj4kUhnxxsp00FcKZ6aNG1FlUP+/3D5KvwYXLNGxqyzNPUmYjqYiZfYidw28KyVxRmgn7FTYf5AmvASZnqNlliMnLZ4g+tmTDPC+ux36/Ih2DCBbcTaT84gA26S3vbtED0HNKNGtgXVoUCM3A/dkXx4T9y5Jpb1eu4nDwJTXEK1d6Xau0EO7o99agZWrtfZMfu8cAfOofXS2UhfZoF02zKCq/WyFdGt6GorwgwcHOIOrBqaS74UNcwti2oSq+YtQJMEMXcisXmRWOPjGKNTvC8q6qGJ2gMkl/w611mu0WVIH9imHQxzS/bpL7bkrs2z66x4tfg9XEAzKboA1/zXnLKksfuipzrvEGGuX9VITC61aSirTSPpSvADBVXha6rGHeCkjsLUNY/IE+y2bTiG3YjNzihZ4ezfjmB5UlkSEdTcUoEK2hxbfea/gtD8WfDhH8zjE0BeGAAA"; }
        }
    }
}
